### PR TITLE
Reset seed before each test, ensure independence of order

### PR DESCRIPTION
**Pull request by querwurzel**
My additional tests caused the following tests to fail. Now every test can run independent of order.

### CODE REVIEW

**Comment by querwurzel** [comment]
What do you think of it?

**Comment by schalkventer** [comment]
Looks good to me!

**Comment by querwurzel** [comment]
Would appreciate a new release soon as we rely on those changes and your lib :)

**Comment by schalkventer** [comment]
That is great to hear! Would love to see how you use it!

**Comment by schalkventer** [comment]
@querwurzel Version 1.3.7 is building as we speak. :)

**Comment by querwurzel** [comment]
Well, we found fakerE.frequency to be useful to emulate other probability distributions than a uniform distribution (Math.random).

**Comment by schalkventer** [comment]
@querwurzel Happy to let you know 1.4.0 is out! Thanks for the contributions, super appreciated! 🎉

Note that is now goes under `faker-extra` and no longer `faker-enhanced`, so you might need to re-add it via NPM: https://www.npmjs.com/package/faker-extra

**Pull request merged**
